"""Remove unique constraint from password

Revision ID: 4eff025360ed
Revises: 2c7ee7d43078
Create Date: 2026-07-20 13:26:58.297628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eff025360ed'
down_revision = '2c7ee7d43078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_password'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_password'), ['password'])

    # ### end Alembic commands ###
