"""Change date_of_birth to Date

Revision ID: d2bf59753a0f
Revises: a4d9e2c7b1f0
Create Date: 2026-07-30 09:41:07.610739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bf59753a0f'
down_revision = 'a4d9e2c7b1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('users')
    op.drop_table('bookings')
    op.drop_table('trains')
    op.drop_table('schedules')
    op.drop_table('payments')
    op.drop_table('user_favourites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favourites',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('train_id', sa.INTEGER(), nullable=False),
    sa.Column('station_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_user_favourites_station_id_stations')),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_user_favourites_train_id_trains')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favourites_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'train_id', 'station_id', name=op.f('pk_user_favourites'))
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.VARCHAR(length=13), nullable=False),
    sa.Column('card_last4', sa.VARCHAR(length=4), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('train_id', sa.INTEGER(), nullable=False),
    sa.Column('from_station_id', sa.INTEGER(), nullable=False),
    sa.Column('to_station_id', sa.INTEGER(), nullable=False),
    sa.Column('departure_time', sa.TIME(), nullable=False),
    sa.Column('arrival_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('platform', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], name=op.f('fk_schedules_from_station_id_stations')),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], name=op.f('fk_schedules_to_station_id_stations')),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_schedules_train_id_trains')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total_seat', sa.INTEGER(), nullable=False),
    sa.Column('available_seat', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_ref', sa.TEXT(), nullable=False),
    sa.Column('passenger_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('train_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('seat_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fare', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('from_station', sa.VARCHAR(length=100), nullable=False),
    sa.Column('to_station', sa.VARCHAR(length=100), nullable=False),
    sa.Column('departure_time', sa.TIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_bookings_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_bookings_train_id_trains')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref', name=op.f('uq_bookings_booking_ref')),
    sa.UniqueConstraint('email', name=op.f('uq_bookings_email'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number'))
    )
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('train_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('platform', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number', name=op.f('uq_stations_train_number'))
    )
    # ### end Alembic commands ###
