"""Change date_of_birth to Date

Revision ID: d2bf59753a0f
Revises: a4d9e2c7b1f0
Create Date: 2026-07-30 09:41:07.610739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bf59753a0f'
down_revision = 'a4d9e2c7b1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column(
        'users',
        'date_of_birth',
        existing_type=sa.DateTime(),
        type_=sa.Date(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'date_of_birth',
        existing_type=sa.Date(),
        type_=sa.DateTime(),
        existing_nullable=False
    )